### ISSUE TITLE
in certain blogger templates do not work

### ISSUE THREAD

**Issue by Krisnantohero** [jessegavin/jQuery-Chord-Transposer#10]
I've tried to code this plugin transpose in one blogger template can not appear the key choice. whereas in other blog templates the change of key can appear. this why why in a particular template does not appear?

**Comment by Krisnantohero** [comment]
examples of blog templates that do not work with this plugin htt*://newjohnywussv3.blogsp*t.co.id

**Comment by jessegavin** [comment]
It's hard to say why it doesn't work in your blogger template without seeing specific error information.

**Comment by Krisnantohero** [comment]
Thank you for the reply, this can already be mr. gavin, it turns out this is because of jquery conflict issues.

sorry again i want to ask, we have been successful before by changing lyrics according to our wish by adding [span.d] then how to [span.c] we change completely with other font (eg courier new font), and for font display on desktop version and mobile version alike? because if still with the default version [span.c] display in the mobile version spacing between words [span.c] is still not regular. 
Thank you very much,

**Comment by Krisnantohero** [comment]
Already sorted mr. Gavin is just an edit in css pre {.
Thank you very much for the jquery. success continues for you. Regards,
