### ISSUE TITLE
Yazı Fontu Sorunu

### ISSUE THREAD

**Issue by iemecen** [jessegavin/jQuery-Chord-Transposer#11]
Hello

pre data-key="A"

"Am Em F"
"lyrics"

</pre>
<script type="text/javascript" src="jquery.min.js"></script>
<script type="text/javascript" src="jquery.transposer.js"></script>
<script type="text/javascript">
    $(function() {
    	$("pre").transpose();
    });
  </script>

When I write this code, it works fine on my page.

but the writings I write in the pre-code are in the form of a typewriter.

I think monospace font

When I do the above encoding I want the pre codes to be in the open sans sans serif font.

athank you.

**Comment by jessegavin** [comment]
Right now this project only works with monospace fonts because each character takes up the exact same horizontal width.

There are ways to render the song using normal variable-width fonts, but it would take a fair amount of work.
