### ISSUE TITLE
Norton Safe Web Warning

### ISSUE THREAD

**Issue by torqueville** [jessegavin/jQuery-Chord-Transposer#15]
I get a warning from Norton Norton Safe Web when visiting 

https://jquery-chord-transposer.now.sh/

"Computer Threats: 7
Identity Threats: 2
Annoyance factors: 0
Total threats on this site: 9"
https://safeweb.norton.com/report/show?url=https://jquery-chord-transposer.now.sh/

**Comment by jessegavin** [comment]
It's probably because I am linking to Google's CDN for jQuery

`<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>`

I am not going to worry about it.
