### ISSUE TITLE
M7 (major 7th) chord is not working

### ISSUE THREAD

**Issue by ljfreelancer88** [jessegavin/jQuery-Chord-Transposer#17]
Hi, I tried the CM7 instead of Cmaj7 but it's not working. 

I'm also using this kind of approach to lay-out my chords, but it's not working either.
[Intro]
Dsus  /  Em  /  | CM7 /  /  / |

**Comment by jessegavin** [comment]
I realize this is almost 2 years after the fact, but I just updated the code to support chords with `M7`, `M9`, `M11`.

**Comment by harshajayman** [comment]
Hi Jess
I am still struggling to get this implemented on Wordpress 
Thanks

Harsha Jayamanne
