### ISSUE TITLE
It is not showing keys in blogger.

### ISSUE THREAD

**Issue by abraham891** [jessegavin/jQuery-Chord-Transposer#19]
The selecting menu keys are not showing in blogger. It only displays the song and chords written in pre tag. Nothing else.

**Comment by jessegavin** [comment]
What is `blogger` ?

**Comment by abraham891** [comment]
`Blogger` is a blog-publishing service that allows multi-user blogs with time-stamped entries. It was developed by Pyra Labs, which was bought by Google in 2003.

**Comment by abraham891** [comment]
[Blogger](https://www.blogger.com) uses HTML, CSS and javascript or jQuery to create website pages.

**Comment by abraham891** [comment]
You can see here [JSFIDDLE](https://jsfiddle.net/hv8dpct4/)
