### ISSUE TITLE
Add reset Button ?

### ISSUE THREAD

**Issue by jcdevz-dev** [jessegavin/jQuery-Chord-Transposer#21]
Add the **reset** button of the key. the purpose also is to make the number of button keys even (17 buttons + reset button)

**Comment by ernitish** [comment]
I have made wordpress plugin, and there i have made reset button too
you can check on my client site-
https://songs.lt/j-jarutis/alright-justinas-jarutis-ir-jessica-shy/

i was using 11 chords key according to client requirements.

**Comment by taufik7000** [comment]
can anyon help me to customize button?

**Comment by ernitish** [comment]
you can contact me here
Skype- @webcast.technology
