### ISSUE TITLE
Start key

### ISSUE THREAD

**Issue by vejzovicm** [jessegavin/jQuery-Chord-Transposer#24]
How can I get start key from "select form" like here http://www.chrisperez.info/transposer/# ? I have WordPress site and script works great, but I need this to make it easier for other users to publish posts.

**Comment by jessegavin** [comment]
Instead of submitting the form back to the server, you can do all of this with javascript in the browser.

Since this plugin requires jQuery, you can use jQuery to accomplish this.

![CleanShot 2022-04-11 at 20 15 41@2x](https://user-images.githubusercontent.com/78791/162859158-5a8be4b6-5364-4364-a3c1-ac9cc304257b.png)

Replace the line highlighted in the screenshot with the following code.

```
$("form").submit(function(e) {
  e.preventDefault();

  // Remove the transpose menu (if it exists)
  $(".transpose-keys").remove();
    
  // store the value of the root key from the <select>
  var root = $("#rootkey").val();

  // store the value of the textarea
  var text = $("textarea.content").val();

  // make a reference to the <pre> element
  var pre = $("pre");

  // populate the <pre> element with the song text.
  pre.text(text).transpose({ key : root });
})
```

**Comment by vejzovicm** [comment]
Thank you for answer. Here I create Post Form with wordpress plugin User Frontend. When someone wants to post a song on my website, I want the ‘data-key’ to be one of the "multi select' keys what he wants. Is that possible?
Screenshot from my site:
![Screenshot 2022-04-12 at 15 27 24](https://user-images.githubusercontent.com/103223026/162975160-df0dea93-63e6-4998-a658-2709d475ef03.png)

**Comment by jessegavin** [comment]
Yes, it's totally possible, but you'll have to do that work yourself in Wordpress, this library is javascript only.

You shouldn't allow users to enter song text into a rich text editor (like you are currently doing for `Post Content`). 
It should be a plain <textarea> element.

I don't know how your Wordpress site works, nor how the "User Frontend" plugin works, but if you follow the documentation for this project you'll see that all you really need to do is to populate render the `data-key` attribute whenever you render out the song content on your page.

```
<pre data-key="{song-key}">
  {post-content}
</pre>
```

**Comment by vejzovicm** [comment]
Thank you very much. Script is amazing.
