### ISSUE TITLE
Transpose fails when over a sharp/flat in Regex Group 2. Also missing maj7/maj9/maj11/maj13 from valid chord match.

### ISSUE THREAD

**Issue by TEZMan** [jessegavin/jQuery-Chord-Transposer#28]
Transpose doesn't recognize a valid chord when over a chord, such as "D/F#m". This can be fixed by adding (?1) before the *. Also added the missing maj chord matches, see below.

`    chordRegex: /^[A-G][b\#]?(2|4|5|6|7|9|11|13|6\/9|7\-5|7\-9|7\#5|7\#9|7\+5|7\+9|b5|#5|#9|7b5|7b9|7sus2|7sus4|add2|add4|add9|aug|dim|dim7|m\/maj7|m6|m7|m7b5|m9|m11|m13|maj7|maj9|maj11|maj13|M7|M9|M11|M13|mb5|m|sus|sus2|sus4)*(\/[A-G][b\#]*(?1)*)*$/`

**Comment by jessegavin** [comment]
I've never seen a guitar chord that had `m` after the slash. I am not a music theorist, but if you can provide me with some article that shows it's valid to put a chord name (which is what `F#m` is) after the slash I'll take a look.

<img width="811" alt="CleanShot 2023-06-08 at 14 20 30@2x" src="https://github.com/jessegavin/jQuery-Chord-Transposer/assets/78791/db19050c-cc40-4855-87aa-2dc024ff9c2b">
https://classicalguitarshed.com/slash-chords-inversions-guitar/

**Comment by TEZMan** [comment]
You are likely correct. I'm not sure where the chord sheet came from, but it was likely a typo on the original I copied from, but I can't seem to find it notated the way I had it anywhere. I know there are bass chords, but I'm not sure how that would be notated. Either way, I really appreciate your transposer and have been using it for years, thank you.

**Comment by jessegavin** [comment]
Glad to hear you've found it useful.

I am working on rewriting the whole thing into a more modern Javascript project that won't require jQuery.

Hopefully I'll get around to releasing that soon
