### ISSUE TITLE
Some chords not recognized

### ISSUE THREAD

**Issue by filipblaauw** [jessegavin/jQuery-Chord-Transposer#4]
I'm having trouble with some chords, and I have not yet figured out the pattern yet.

m7b5, sus4, m7#5, 7#9 are some of the chords where only part of the chords are wrapped in the span. On transpose, the parts that's not in the span, is skipped.

![skjermbilde 2016-07-04 kl 22 28 39](https://cloud.githubusercontent.com/assets/7829955/16569433/b4623f8a-4236-11e6-94d3-a83bc5a934ff.png)

Update: I got it working by adding 4, b5 and #5 to the regex list.

**Comment by jessegavin** [comment]
Those are some funky chords. You're right, they're probably missing from the Regex.

Would you be willing to submit a pull request?  If not, just let me know where how you changed the Regex and I can implement it.

Thanks for posting this.

**Comment by filipblaauw** [comment]
I've submitted a PR
